<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $paket = Category::where('slug', 'paket')->first();
        $lauk = Category::where('slug', 'lauk')->first();
        $sotoLainnya = Category::where('slug', 'soto-lainnya')->first();
        $minuman = Category::where('slug', 'minuman')->first();
        $sambalEkstra = Category::where('slug', 'sambal-ekstra')->first();

        $items = [
            // PAKET
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Paha Bawah',
                'slug' => 'nasi-paha-bawah',
                'description' => 'Paket Nasi Putih + Paha Bawah Ayam Penyet + Sambal Bawang/Tomat + Lalap.',
                'price' => 15000,
                'image_url' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Paha Atas',
                'slug' => 'nasi-paha-atas',
                'description' => 'Paket Nasi Putih + Paha Atas Ayam Penyet + Sambal + Lalap.',
                'price' => 17000,
                'image_url' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Dada',
                'slug' => 'nasi-dada',
                'description' => 'Paket Nasi Putih + Dada Ayam Penyet Gurih + Sambal + Lalap.',
                'price' => 23000,
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => false,
                'is_recommended' => true,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Tepong',
                'slug' => 'nasi-tepong',
                'description' => 'Paket Nasi Putih + Tepong Ayam Spesial + Sambal + Lalapan.',
                'price' => 25000,
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Sayap',
                'slug' => 'nasi-sayap',
                'description' => 'Paket Nasi Putih + Sayap Ayam Penyet + Sambal + Lalap.',
                'price' => 12000,
                'image_url' => 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Lele',
                'slug' => 'nasi-lele',
                'description' => 'Paket Nasi Putih + Lele Goreng Penyet Crispy + Sambal + Lalap.',
                'price' => 15000,
                'image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Mujair',
                'slug' => 'nasi-mujair',
                'description' => 'Paket Nasi Putih + Ikan Mujair Goreng Penyet + Sambal + Lalap.',
                'price' => 25000,
                'image_url' => 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Kulit',
                'slug' => 'nasi-kulit',
                'description' => 'Paket Nasi Putih + Kulit Ayam Goreng Garing Penyet + Sambal + Lalap.',
                'price' => 10000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Terong Crispy',
                'slug' => 'nasi-terong-crispy',
                'description' => 'Paket Nasi Putih + Terong Crispy Renyah + Sambal + Lalap.',
                'price' => 10000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 1,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Tahu Tempe',
                'slug' => 'nasi-tahu-tempe',
                'description' => 'Paket Nasi Putih + Tahu & Tempe Penyet Cobek + Sambal + Lalap.',
                'price' => 9000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 1,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Telur',
                'slug' => 'nasi-telur',
                'description' => 'Paket Nasi Putih + Telur Penyet (Dadar/Ceplok) + Sambal + Lalap.',
                'price' => 9000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 1,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Ati',
                'slug' => 'nasi-ati',
                'description' => 'Paket Nasi Putih + Ati Ampela Penyet + Sambal + Lalap.',
                'price' => 11000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $paket->id,
                'name' => 'Nasi Kepala',
                'slug' => 'nasi-kepala',
                'description' => 'Paket Nasi Putih + Kepala Ayam Penyet + Sambal + Lalap.',
                'price' => 10000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],

            // LAUK SATUAN
            [
                'category_id' => $lauk->id,
                'name' => 'Paha Bawah',
                'slug' => 'paha-bawah',
                'description' => 'Ayam Paha Bawah Goreng / Bakar bumbu rempah.',
                'price' => 10000,
                'image_url' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Paha Atas',
                'slug' => 'paha-atas',
                'description' => 'Ayam Paha Atas Goreng bumbu meresap.',
                'price' => 12000,
                'image_url' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Tepong',
                'slug' => 'tepong',
                'description' => 'Tepong Ayam Goreng empuk nikmat.',
                'price' => 20000,
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Sayap',
                'slug' => 'sayap',
                'description' => 'Sayap Ayam Goreng bumbu rempah.',
                'price' => 7000,
                'image_url' => 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Ati Ampela',
                'slug' => 'ati-ampela',
                'description' => 'Ati Ampela Ayam Goreng.',
                'price' => 6000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Kepala Ayam',
                'slug' => 'kepala-ayam',
                'description' => 'Kepala Ayam Goreng bumbu ungkep.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Kulit Ayam',
                'slug' => 'kulit-ayam',
                'description' => 'Kulit Ayam Goreng Crispy garing gurih.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Ceker Ayam (Isi 3)',
                'slug' => 'ceker-ayam-isi-3',
                'description' => 'Ceker Ayam empuk gurih isi 3 biji.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Tahu Goreng',
                'slug' => 'tahu-goreng',
                'description' => 'Tahu Goreng lembut gurih.',
                'price' => 2000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Tempe Goreng',
                'slug' => 'tempe-goreng',
                'description' => 'Tempe Bacem/Goreng gurih.',
                'price' => 2000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Telur (Goreng/Ceplok)',
                'slug' => 'telur-goreng-ceplok',
                'description' => 'Telur Goreng Dadar atau Ceplok.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Dadar / Ceplok Tambahan',
                'slug' => 'dadar-ceplok-tambahan',
                'description' => 'Tambahan Dadar atau Ceplok.',
                'price' => 3000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Terong Original',
                'slug' => 'terong-original',
                'description' => 'Terong Goreng Original manis segar.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Terong Crispy',
                'slug' => 'terong-crispy',
                'description' => 'Terong Goreng Tepung Crispy renyah.',
                'price' => 6000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => false,
            ],
            [
                'category_id' => $lauk->id,
                'name' => 'Pete Goreng',
                'slug' => 'pete-goreng',
                'description' => 'Pete Goreng harum penambah selera.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],

            // SOTO & LAINNYA
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Soto Kecil',
                'slug' => 'soto-kecil',
                'description' => 'Mangkok Soto Segar Porsi Kecil khas Mbak Puji.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Soto Besar',
                'slug' => 'soto-besar',
                'description' => 'Mangkok Soto Segar Porsi Besar Komplit bertabur koya.',
                'price' => 8000,
                'image_url' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Kuah Soto Alone',
                'slug' => 'kuah-soto-alone',
                'description' => 'Semangkok Kuah Soto hangat beraroma rempah gurih.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Indomie Kuah / Rebus',
                'slug' => 'indomie-kuah-rebus',
                'description' => 'Indomie Kuah hangat gurih lezat.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 1,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Indomie + Telur',
                'slug' => 'indomie-telur',
                'description' => 'Indomie Kuah/Goreng disajikan dengan Telur rebus/ceplok.',
                'price' => 9000,
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 1,
                'is_bestseller' => true,
                'is_recommended' => false,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Nasi Putih (1 Porsi)',
                'slug' => 'nasi-putih-1-porsi',
                'description' => 'Nasi Putih hangat 1 porsi.',
                'price' => 5000,
                'image_url' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Nasi Putih (1.5 Porsi)',
                'slug' => 'nasi-putih-1-5-porsi',
                'description' => 'Nasi Putih hangat 1.5 porsi kenyang.',
                'price' => 8000,
                'image_url' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $sotoLainnya->id,
                'name' => 'Nasi Putih (2 Porsi)',
                'slug' => 'nasi-putih-2-porsi',
                'description' => 'Nasi Putih hangat 2 porsi super puas.',
                'price' => 10000,
                'image_url' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],

            // MINUMAN
            [
                'category_id' => $minuman->id,
                'name' => 'Teh (Es / Hangat)',
                'slug' => 'teh-es-hangat',
                'description' => 'Teh Manis harum manis dingin atau hangat.',
                'price' => 3000,
                'image_url' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $minuman->id,
                'name' => 'Jeruk (Es / Hangat)',
                'slug' => 'jeruk-es-hangat',
                'description' => 'Perasan Jeruk Segar alami manis asam pas penawar pedas.',
                'price' => 4000,
                'image_url' => 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $minuman->id,
                'name' => 'Aneka Kopi',
                'slug' => 'aneka-kopi',
                'description' => 'Kopi Hitam / Kopi Susu hangat/dingin.',
                'price' => 4000,
                'image_url' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $minuman->id,
                'name' => 'Air Mineral (Es / Hangat)',
                'slug' => 'air-mineral-es-hangat',
                'description' => 'Air Mineral segar dingin atau biasa.',
                'price' => 1000,
                'image_url' => 'https://images.unsplash.com/photo-1560023907-5f313c875300?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 0,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],

            // SAMBAL & EKSTRA
            [
                'category_id' => $sambalEkstra->id,
                'name' => 'Sambal Bawang Dadakan',
                'slug' => 'sambal-bawang-dadakan',
                'description' => 'Sambal Bawang Ulek segar pedas tampol (Cabai rawit + Bawang merah).',
                'price' => 3000,
                'image_url' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 3,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
            [
                'category_id' => $sambalEkstra->id,
                'name' => 'Sambal Tomat Dadakan',
                'slug' => 'sambal-tomat-dadakan',
                'description' => 'Sambal Tomat Ulek gurih manis pedas sedang.',
                'price' => 3000,
                'image_url' => 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 1,
                'is_bestseller' => false,
                'is_recommended' => false,
            ],
            [
                'category_id' => $sambalEkstra->id,
                'name' => 'Sambal Campur (Bawang + Tomat)',
                'slug' => 'sambal-campur-bawang-tomat',
                'description' => 'Sensasi Sambal Bawang dicampur Tomat Ulek dadakan.',
                'price' => 4000,
                'image_url' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
                'spicy_level' => 2,
                'is_bestseller' => true,
                'is_recommended' => true,
            ],
        ];

        foreach ($items as $item) {
            MenuItem::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
